### DISCUSSION TITLE
Multiple User Support for Grocy Ingress in Home Assistant

### DISCUSSION THREAD

**Discussion by Graybound** [hassio-addons/addon-grocy#487] [Ideas]
Hello everyone,

I've been exploring the Grocy addon for Home Assistant and came across a potential enhancement that could significantly improve the user experience for households with multiple users.

Currently, I'm using the grocy_ingress_user to link Home Assistant login information with Grocy. My goal is to have seamless integration where, for example, when "mom" opens Grocy inside Home Assistant, she is automatically signed into her Grocy account. Similarly, when "child 1" accesses Grocy from Home Assistant, they are signed into their respective account without needing to log in multiple times.

``` yaml
grocy_ingress_user: dad:password:admin
grocy_ingress_user: mom:password:admin
grocy_ingress_user: child1:password:user
grocy_ingress_user: child2:password:user
grocy_ingress_user: kiosk:Kiosk:user
```

Unfortunately, it appears that the current setup only allows for one user to be added for ingress at a time. If it were possible to support multiple users for ingress, it would streamline the process and enhance the overall user experience for families or shared households.

I am not a professional developer and don't have the time to fork this and learn how to create the feature myself. However, I believe this feature would be a valuable addition to the Grocy addon and would love to hear thoughts or suggestions from the community on this.

Thank you!
