### ISSUE TITLE
Disabling chore assignments breaks ability to add chores to master data

### ISSUE THREAD

**Issue by alexrmay91** [hassio-addons/addon-grocy#153]
# Problem/Motivation

> I do not want to assign chores to a user

## Expected behavior

> _Assignment type_ and _Assign to_ fields are hidden and chores can be added

## Actual behavior

> _Assignment type_ and _Assign to_ fields are hidden and nothing happens when clicking the _Save_ button.

## Steps to reproduce

> My configuration is set to these values. Setting the _chores_assignment_ key to false causes the issue. Setting it to true behaves as expected.
```
culture: en
currency: USD
entry_page: chores
features:
  batteries: false
  calendar: true
  chores: true
  equipment: false
  recipes: false
  shoppinglist: false
  stock: false
  tasks: true
tweaks:
  chores_assignment: false
  multiple_shopping_lists: false
  stock_best_before_date_tracking: false
  stock_location_tracking: false
  stock_price_tracking: false
  stock_product_freezing: false
  stock_product_opened_tracking: false
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
```

## Proposed changes

> I do not have a proposed change. I am just setting the _Assignment type_ field to _No assignment_
