### ISSUE TITLE
No TZ set in php.ini results in UTC times in API

### ISSUE THREAD

**Issue by blue-hound** [hassio-addons/addon-grocy#274]
# Problem/Motivation

> Grocy doesn't handle timezones in anyway. If a timezone isn't set somewhere in PHP code or the php.ini file it defaults to UTC. Therefore, API call times are set to UTC no matter what time is passed via the API. There are very few times passed to the API, but completing chores is one of those API calls.

## Expected behavior

> When passing a time to the API, the local time should be logged. I'm calling the REST commands directly to the Grocy instance for simplicity.

``` yaml
  test_chore:
    url: https://homeassistant.home:9192/api/chores/9/execute
    headers:
      GROCY-API-KEY: !secret GROCY_API_KEY
    method: POST
    content_type: "application/json"
    payload: '{ "tracked_time": "now().strftime(%Y-%m-%d %H:%M:%S)", "user": 0 }'
    verify_ssl: true
```

## Actual behavior

> I've passed so many time strings to Grocy trying to get around this, so many different templates. I passed every type of time format Home Assistant could come up with and they all resulted in UTC time in the chore completion time field. If I pass my local time as the completion time of a chore, Grocy converts it to UTC.

The api call to /api/system/time returns the following:
```json
{
"timezone": "America/Toronto",
"time_local": "2022-01-17 13:25:18",
"time_local_sqlite3": "2022-01-17 13:25:18",
"time_utc": "2022-01-17 18:25:18",
"timestamp": 1642443918,
"offset": 0
}
```
## Steps to reproduce

> API call to /api/chores/\<chore number\>/execute
``` json
{
  "tracked_time": "2021-01-24 07:06:59",
  "done_by": 0
}
```

## Proposed changes

> Add a timezone config entry to Home Assistant or use the TZ environment variable (easiest?) that is passed to the docker to patch the php.ini file located in /etc/php8/php.ini to add
```php
date.timezone = \<timezone\>
```
If precedence would allow /etc/php8/conf.d/99-grocy.ini might be easier to modify since it's already in the repository. Just need to add [date] as well.

The first suggestion fixed the problem on my end and the payload that I pasted above for my test chore now tracks in my timezone.
