### ISSUE TITLE
Not able to adjust inventory and log not displaying anything

### ISSUE THREAD

**Issue by tortho** [hassio-addons/addon-grocy#378]
Grocy 0.19.1 in HASOS 2023.7.3, Supervisor 2023.07.1, OS 10.3

Logging in, working with masterdata all works fine.
Changing quantity in inventory however ends up in an endless save (circle spinning after pressing OK)

Log level set to Trace but nothing in the addon log whatever I do in the addon.

My Config:
``````
culture: "no"
currency: NOK
entry_page: stock
features:
  batteries: false
  calendar: false
  chores: false
  equipment: false
  recipes: true
  shoppinglist: true
  stock: true
  tasks: true
tweaks:
  chores_assignment: true
  multiple_shopping_lists: true
  stock_best_before_date_tracking: true
  stock_location_tracking: true
  stock_price_tracking: false
  stock_product_freezing: true
  stock_product_opened_tracking: true
  stock_count_opened_products_against_minimum_stock_amount: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
grocy_ingress_user: ""
log_level: trace
``````
