### ISSUE TITLE
Grocy Startup hangs after Nginx attempts to start.

### ISSUE THREAD

**Issue by grayplex** [hassio-addons/addon-grocy#414]
# Problem/Motivation

Add-on does not start

## Expected behavior

Add-on starts and stays running

## Actual behavior

Startup hangs after starting NGINX 

### Addon log
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.20.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.3
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-php-fpm: starting
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-grocy: starting
[17:01:42] DEBUG: Data directory not initialized, doing that now...
[17:01:42] DEBUG: Symlinking data directory to persistent storage location...
[17:01:42] INFO: Patching Grocy to fix relative URL handling...
patching file views/layout/default.blade.php
s6-rc: info: service init-grocy successfully started
s6-rc: info: service init-php-fpm successfully started
s6-rc: info: service php-fpm: starting
s6-rc: info: service php-fpm successfully started
[17:01:43] INFO: Starting PHP-FPM...
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[17:01:45] INFO: Starting NGinx....
```
### Supervisor log
```
23-11-29 17:00:47 INFO (MainThread) [supervisor.addons.addon] Creating Home Assistant add-on data folder /data/addons/data/a0d7b954_grocy
23-11-29 17:00:47 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/grocy/amd64 with tag 0.20.1.
23-11-29 17:01:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 257
23-11-29 17:01:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-11-29 17:01:14 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_grocy' successfully installed
23-11-29 17:01:40 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/grocy/amd64 with version 0.20.1
23-11-29 17:03:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-11-29 17:03:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-11-29 17:03:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-11-29 17:03:24 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-11-29 17:03:30 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
23-11-29 17:03:30 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
23-11-29 17:03:40 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Grocy to start, took more than 120 seconds
```
### Grocy config, left at default.
```
culture: en
currency: USD
entry_page: stock
features:
  batteries: true
  calendar: true
  chores: true
  equipment: true
  recipes: true
  shoppinglist: true
  stock: true
  tasks: true
tweaks:
  chores_assignment: true
  multiple_shopping_lists: true
  stock_best_before_date_tracking: true
  stock_location_tracking: true
  stock_price_tracking: true
  stock_product_freezing: true
  stock_product_opened_tracking: true
  stock_count_opened_products_against_minimum_stock_amount: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
grocy_ingress_user: ""
log_level: debug
```

## Steps to reproduce

Uninstall add-on and re-install
